# Generated by Django 5.1.4 on 2024-12-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="cover",
        ),
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
    ]
